require: rubocop/devtools

Devtools/AnnotateNamespace:
  Description: 'Check that the ends of modules and classes are annotated'
  Enabled: true
Devtools/SpecifyIt:
  Description: 'Check for RSpec specs using `it do`'
  Enabled: true
Devtools/NamedSubject:
  Description: 'Name your RSpec subject if you reference it explicitly'
  Enabled: true
Devtools/LeadingSubject:
  Description: 'Declare your RSpec test subject before let declarations'
  Enabled: true
